Train_config: 
  batch_size: 32
  shuffle: True
  num_workers: 4
  pin_memory: True
  drop_last: True
  epochs: 100
  lr: 0.001
  model_name: gans 
  version : 1
  save_model: True
  save_at: 10
  sample_step: 100

Dir: 
  root: GAN_s 
  dataset : data\humanface\
  model_save_path : artifects\
  model_load_path : artifects\



Generol_config : 
  feature_dis : 64
  feature_gen : 64
  latent_dim : 100


Discriminator: 
  name: Discriminator
  params: 
    in_channels: 3
    out_channels: 1
    kernel_size: 4
    stride: 2
    padding: 1
    bias: False
    feature_dis: 64
    batch_norm: True
    dropout: 0.5
  

Pre_process: 
  image_size: 64
  in_channels: 3 
  out_channels: 64






